### ISSUE TITLE
Contributions dissapear after submission

### ISSUE THREAD

**Issue by olesm** [engagelab/talkwall#278]
Hi Louis,
I'm in a session and have set up TalkWall fine but when the learners write a message and hit the + button, it is not going onto the wall - it just disappears.
 
--
Many thanks,

Mrs Cording
Honywood School, English department.

**Comment by nesnass** [comment]
This occurred during a period of high activity 19th Jan  ~09:45am
Server averaged 132 rpm (2 requests per second is not much is it?!)
Many requests timed out at this point including no-db requests such as poll/*/*/*/none/new
The app was down (crashed) yesterday from 09:23am -09:34am
The timeouts were not due to the crash, they were deliberate as the server considered itself 'too busy'.  Code was stopping polling on this request but not restarting. New 'toast' code added to help this issue, polling should delay before restarting again.
